#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

export LD_LIBRARY_PATH="$script_dir${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
exec "$script_dir/hypersync.bin" "$@"
